# triggers workflow on push or pull request events for master branch

# on:
#   push:
#     branches: [ main ]

# jobs:
#   build:
#     runs-on: ubuntu-latest
    
#     steps:
#       - uses: actions/checkout@v2
#       - name: whatsapp
#         run: echo 'Start!'
#         env:
#           account_sid: ${{ secrets.account_sid }}
#           auth_token: ${{ secrets.auth_token }}
#           contact_no: ${{ secrets.contact_no }}
